version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 10.16.0
  build:
    commands:
      - node --version
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main.css
    - images/*