version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm install
      - npm run webpack

artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main.css
    - images/*
    - dist/bundle.js
    - content/RichardSirokmanDevOpsResume2019.html
    - content/RichardSirokmanDevOpsResume2019.pdf
    - content/images/image1.jpg
    - content/images/image2.png
    - content/images/image3.png